import { Emotion, EmotionCategory } from '../types/emotion';

export const emotionCategories: EmotionCategory[] = [
  {
    id: 'friendly',
    title: '友好满足',
    description: '猫咪感到愉悦、满足或友好',
  },
  {
    id: 'attention',
    title: '吸引注意',
    description: '猫咪想要引起您的注意',
  },
  {
    id: 'warning',
    title: '威胁警告',
    description: '猫咪感到不安、生气或想要警告',
  },
];

export const emotions: Emotion[] = [
  {
    id: 'call',
    icon: '😺',
    title: '友好呼唤',
    description: '友好得呼唤对方猫咪',
    audioFile: '../../audios/call.MP3',
    categoryId: 'friendly',
  },
  {
    id: 'comfortable',
    icon: '😌',
    title: '舒适',
    description: '您的猫咪感到舒适和放松。',
    audioFile: '../../audios/comfortable.MP3',
    categoryId: 'friendly',
  },
  {
    id: 'flighty',
    icon: '🥰',
    title: '撒娇',
    description: '撒娇的呼唤对方猫咪',
    audioFile: '../../audios/flighty.MP3',
    categoryId: 'friendly',
  },
  {
    id: 'satisfy',
    icon: '😊',
    title: '满足',
    description: '你感到满足',
    audioFile: '../../audios/satisfy.MP3',
    categoryId: 'friendly',
  },
  {
    id: 'yummy',
    icon: '😋',
    title: '美味',
    description: '你感到美味',
    audioFile: '../../audios/yummy.MP3',
    categoryId: 'friendly',
  },
  {
    id: 'hello',
    icon: '👋',
    title: '打招呼',
    description: '友好打招呼、撒娇',
    audioFile: '../../audios/hello.MP3',
    categoryId: 'attention',
  },
  {
    id: 'for_food',
    icon: '🍽️',
    title: '需求食物',
    description: '问候，对食物有需求',
    audioFile: '../../audios/for_food.MP3',
    categoryId: 'attention',
  },
  {
    id: 'ask_for_play',
    icon: '🎭',
    title: '邀请玩耍',
    description: '邀请玩耍',
    audioFile: '../../audios/ask_for_play.MP3',
    categoryId: 'attention',
  },
  {
    id: 'ask_for_hunting',
    icon: '🐁',
    title: '邀请狩猎',
    description: '兴奋、捕猎',
    audioFile: '../../audios/ask_for_hunting.MP3',
    categoryId: 'attention',
  },
  {
    id: 'discomfort',
    icon: '😣',
    title: '委屈',
    description: '委屈、不舒服、别弄我',
    audioFile: '../../audios/discomfort.MP3',
    categoryId: 'attention',
  },
  {
    id: 'find_mom',
    icon: '🐈',
    title: '求助/找妈妈',
    description: '求助/找妈妈',
    audioFile: '../../audios/find_mom.MP3',
    categoryId: 'attention',
  },
  {
    id: 'anxious',
    icon: '😰',
    title: '焦虑/害怕',
    description: '焦虑/害怕',
    audioFile: '../../audios/anxious.MP3',
    categoryId: 'attention',
  },
  {
    id: 'courtship',
    icon: '💕',
    title: '求偶',
    description: '求偶',
    audioFile: '../../audios/courtship.MP3',
    categoryId: 'attention',
  },
  {
    id: 'curious',
    icon: '🤔',
    title: '敷衍、好奇',
    description: '敷衍、好奇',
    audioFile: '../../audios/curious.MP3',
    categoryId: 'attention',
  },
  {
    id: 'goaway',
    icon: '🚫',
    title: '走开！',
    description: '走开！',
    audioFile: '../../audios/goaway.MP3',
    categoryId: 'warning',
  },
  {
    id: 'goout',
    icon: '👉',
    title: '滚开！',
    description: '滚开！',
    audioFile: '../../audios/goout.MP3',
    categoryId: 'warning',
  },
  {
    id: 'dieaway',
    icon: '💀',
    title: '死开！',
    description: '死开！',
    audioFile: '../../audios/dieaway.MP3',
    categoryId: 'warning',
  },
  {
    id: 'warning',
    icon: '⚠️',
    title: '警告、驱逐',
    description: '警告、驱逐',
      audioFile: '../../audios/warning.MP3',
    categoryId: 'warning',
  },
  {
    id: 'unhappy',
    icon: '😒',
    title: '别弄我、不满',
    description: '别弄我、不满',
    audioFile: '../../audios/unhappy.MP3',
    categoryId: 'warning',
  },
  {
    id: 'alert',
    icon: '🚨',
    title: '敌视、警惕',
    description: '敌视、警惕',
    audioFile: '../../audios/alert.MP3',
    categoryId: 'warning',
  },
  {
    id: 'for_fight',
    icon: '🥊',
    title: '强烈警告',
    description: '强烈警告、准备战斗',
    audioFile: '../../audios/for_fight.MP3',
    categoryId: 'warning',
  },
  {
    id: 'scared',
    icon: '😱',
    title: '害怕',
    description: '您的猫咪感到害怕或威胁。',
    audioFile: '../../audios/scared_meow.MP3',
    categoryId: 'warning',
  },
];
